# Generated by Django 4.1.1 on 2022-10-26 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_alter_activovehiculo_fechafinsoat_and_more'),
        ('usuarios', '0001_initial'),
        ('gestionActivos', '0002_remove_generarruta_fkpasajero_detalleruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='descripcionRuta',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fechaRegreso',
            field=models.DateField(blank=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Regreso'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fechaSalida',
            field=models.DateField(blank=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fkUsuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fkVehiculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activovehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='horaSalida',
            field=models.TimeField(blank=True, help_text='HH:MM', verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='kilometrajeFinalVehiculo',
            field=models.IntegerField(blank=True, verbose_name='Kilometraje Final'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='lugarDestino',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lugar de Destino'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='lugarSalida',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lugar de Salida'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='observacionesRuta',
            field=models.TextField(blank=True, max_length=100, verbose_name='Observaciones'),
        ),
    ]
