# Generated by Django 4.1.1 on 2022-10-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0002_alter_generarruta_kilometrajefinalvehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNombrePasajero', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('primerApellidoPasajero', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('tipoDocumento', models.CharField(choices=[('C.C.', 'Cédula de Ciudadania'), ('C.E.', 'Cédula de Extranjería'), ('PASS', 'Pasaporte')], default='C.C.', max_length=5, verbose_name='Tipo de Documento')),
                ('numeroDocumentoPasajero', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('direccionPasajero', models.CharField(max_length=100, verbose_name='Dirección Residencia')),
                ('telefonoPasajero', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fkPasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionActivos.pasajero', verbose_name='Pasajero'),
        ),
    ]
