# Generated by Django 4.1.1 on 2022-11-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0004_remove_registrarmantenimiento_fkidequipooficina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarmantenimiento',
            name='adjuntarArchivoMantenimiento',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
