# Generated by Django 4.1.1 on 2022-11-04 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_foto'),
        ('activos', '0007_alter_activovehiculo_fechafinsoat_and_more'),
        ('gestionActivos', '0008_alter_mantenimientoextintor_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='descripcionRuta',
            field=models.TextField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fechaRegreso',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Regreso'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fechaSalida',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fkUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='fkVehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activovehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='horaRegreso',
            field=models.TimeField(blank=True, help_text='HH:MM', verbose_name='Hora de Regreso'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='horaSalida',
            field=models.TimeField(help_text='HH:MM', verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='lugarDestino',
            field=models.CharField(max_length=50, verbose_name='Lugar de Destino'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='lugarSalida',
            field=models.CharField(max_length=50, verbose_name='Lugar de Salida'),
        ),
    ]
