# Generated by Django 4.1.1 on 2022-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0009_alter_generarruta_descripcionruta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='horaRegreso',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True, verbose_name='Hora de Regreso'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='kilometrajeFinalVehiculo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraje Final'),
        ),
        migrations.AlterField(
            model_name='generarruta',
            name='observacionesRuta',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
    ]
