# Generated by Django 4.1.1 on 2022-11-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0010_alter_generarruta_horaregreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='horaSalida',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True, verbose_name='Hora de Salida'),
        ),
    ]
