# Generated by Django 4.1.1 on 2022-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0011_alter_generarruta_horasalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='horaSalida',
            field=models.TimeField(help_text='HH:MM', verbose_name='Hora de Salida'),
        ),
    ]
