# Generated by Django 4.1.1 on 2022-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0012_alter_generarruta_horasalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='estadoPasajero',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado del pasajero'),
        ),
    ]
