# Generated by Django 4.1.1 on 2022-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0013_pasajero_estadopasajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarruta',
            name='estadoRuta',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('cerrada', 'cerrada')], default='Abierta', max_length=10, verbose_name='Estado de la Ruta'),
        ),
    ]
