# Generated by Django 4.1.1 on 2022-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0014_generarruta_estadoruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='estadoRuta',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'cerrada')], default='Abierta', max_length=10, verbose_name='Estado de la Ruta'),
        ),
    ]
