# Generated by Django 4.1.1 on 2022-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0015_alter_generarruta_estadoruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='estadoRuta',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10, verbose_name='Estado de la Ruta'),
        ),
    ]
