# Generated by Django 4.1.1 on 2022-11-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0016_alter_generarruta_estadoruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='kilometrajeFinalVehiculo',
            field=models.IntegerField(default=0, verbose_name='Kilometraje Final'),
        ),
    ]
