# Generated by Django 4.1.1 on 2022-11-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0017_alter_generarruta_kilometrajefinalvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarmantenimiento',
            name='descripcionMantenimiento',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
    ]
