# Generated by Django 4.1.1 on 2022-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0019_alter_generarruta_descripcionruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarruta',
            name='observacionesRuta',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones'),
        ),
    ]
