# Generated by Django 4.1.1 on 2022-11-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0021_activoequipooficina_fechaingresoequipo_and_more'),
        ('gestionActivos', '0020_alter_generarruta_observacionesruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkEquipoOficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activoequipooficina', verbose_name='Equipo de Oficina')),
                ('fkExtintor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activoextintor', verbose_name='Extintor')),
                ('fkVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activovehiculo', verbose_name='Vehículo')),
            ],
        ),
        migrations.DeleteModel(
            name='GenerarAlarma',
        ),
    ]
