# Generated by Django 4.1.1 on 2022-10-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundoNombre', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('tipoDocumento', models.CharField(choices=[('C.C.', 'Cédula de Ciudadania'), ('C.E.', 'Cédula de Extranjería'), ('PASS', 'Pasaporte')], default='C.C.', max_length=5, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('numeroTelefono', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('ciudadResidencia', models.CharField(max_length=50, verbose_name='Ciudad de Residencia')),
                ('direccionResidencia', models.CharField(max_length=100, verbose_name='Dirección de Residencia')),
                ('correoElectronico', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], default='Otro', max_length=20, verbose_name='Genero')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('fechaRegistro', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Registro')),
                ('tipoUsuario', models.CharField(choices=[('Funcionario', 'Funcionario'), ('Conductor', 'Conductor'), ('Administrador', 'Administrador')], default='Funcionario', max_length=20, verbose_name='Tipo de Usuario')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
