# Generated by Django 4.1.1 on 2022-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correoElectronico',
            field=models.EmailField(max_length=100, verbose_name='Correo Electronico'),
        ),
    ]
