# Generated by Django 4.1.1 on 2022-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='segundoApellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundoNombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Segundo Nombre'),
        ),
    ]
