# Generated by Django 4.1.1 on 2022-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='media/usuarios/default.jpg', upload_to='media/usuarios'),
        ),
    ]
