# Generated by Django 4.1.1 on 2022-10-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_segundoapellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permisos',
        ),
    ]
