# Generated by Django 4.1.1 on 2022-10-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoEquipoOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialEquipo', models.CharField(max_length=50, verbose_name='Serial Equipo')),
                ('marcaEquipo', models.CharField(max_length=20, verbose_name='Marca Equipo')),
                ('colorEquipo', models.CharField(max_length=20, verbose_name='Color Equipo')),
                ('sistemaOperativo', models.CharField(blank=True, max_length=20, verbose_name='Sistema Operativo')),
                ('ramEquipo', models.CharField(blank=True, max_length=20, verbose_name='Ram del Equipo')),
                ('memoriaEquipo', models.CharField(blank=True, max_length=20, verbose_name='Memoria del Equipo')),
                ('ubicacionEquipo', models.CharField(max_length=50, verbose_name='Ubicación del Equipo')),
                ('componentesAdicionales', models.TextField(blank=True, max_length=100, verbose_name='Componentes del Equipo')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='ActivoExtintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialExtintor', models.CharField(max_length=50, verbose_name='Serial Extintor')),
                ('colorExtintor', models.CharField(max_length=20, verbose_name='Color Extintor')),
                ('ubicacionExtintor', models.CharField(max_length=50, verbose_name='Ubicación del Extintor')),
                ('tipoExtintor', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo C')], default='A', max_length=5, verbose_name='Tipo de Extintor')),
                ('pesoExtintor', models.CharField(max_length=10, verbose_name='Peso del Extintor')),
            ],
        ),
        migrations.CreateModel(
            name='ActivoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaVehiculo', models.CharField(max_length=20, verbose_name='Marca del Vehículo')),
                ('modeloVehiculo', models.CharField(max_length=10, verbose_name='Modelo del Vehículo')),
                ('placaVehiculo', models.CharField(max_length=10, unique=True, verbose_name='Placa del Vehículo')),
                ('colorVehiculo', models.CharField(max_length=20, verbose_name='Color del Vehículo')),
                ('serialVehiculo', models.CharField(max_length=50, verbose_name='Serial del Vehiculo')),
                ('tipoCombustible', models.CharField(max_length=20, verbose_name='Tipo de Combustible')),
                ('cantidadPasajeros', models.CharField(max_length=5, verbose_name='Cantidad de Pasajeros')),
                ('personaEncargadaVehiculo', models.CharField(max_length=50, verbose_name='Persona a Cargo')),
                ('estadoVehiculo', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=10, verbose_name='Estado del Vehículo')),
                ('fechaIngresoVehiculo', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Ingreso')),
                ('fechaInicioSoat', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Inicio Soat')),
                ('fechaFinSoat', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Vencimiento Soat')),
                ('fechaInicioTecnicomecanica', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Inicio Tecnicomecanica')),
                ('fechaVencimientoTecnicomecanica', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha Vencimiento Tecnicomecanica')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
