# Generated by Django 4.1.1 on 2022-10-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activoequipooficina',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='activovehiculo',
            name='estado',
        ),
    ]
