# Generated by Django 4.1.1 on 2022-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivos', '0003_pasajero_alter_generarruta_fkpasajero'),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasajero',
        ),
        migrations.AlterField(
            model_name='activoequipooficina',
            name='componentesAdicionales',
            field=models.TextField(blank=True, max_length=100, verbose_name='Componentes del Equipo'),
        ),
        migrations.AlterField(
            model_name='activoequipooficina',
            name='memoriaEquipo',
            field=models.CharField(blank=True, default='No Aplica', max_length=20, verbose_name='Memoria del Equipo'),
        ),
        migrations.AlterField(
            model_name='activoequipooficina',
            name='ramEquipo',
            field=models.CharField(blank=True, default='No Aplica', max_length=20, verbose_name='Ram del Equipo'),
        ),
        migrations.AlterField(
            model_name='activoequipooficina',
            name='sistemaOperativo',
            field=models.CharField(blank=True, default='No Aplica', max_length=20, verbose_name='Sistema Operativo'),
        ),
    ]
