# Generated by Django 4.1.1 on 2022-10-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_rename_estado_activoequipooficina_estadoequipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activovehiculo',
            name='condicionVehiculo',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=10, verbose_name='Condicion del Vehículo'),
        ),
    ]
