# Generated by Django 4.1.1 on 2022-10-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_alter_activovehiculo_condicionvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activovehiculo',
            name='fechaFinSoat',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha Vencimiento Soat'),
        ),
        migrations.AlterField(
            model_name='activovehiculo',
            name='fechaIngresoVehiculo',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='activovehiculo',
            name='fechaInicioSoat',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha Inicio Soat'),
        ),
        migrations.AlterField(
            model_name='activovehiculo',
            name='fechaInicioTecnicomecanica',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha Inicio Tecnicomecanica'),
        ),
        migrations.AlterField(
            model_name='activovehiculo',
            name='fechaVencimientoTecnicomecanica',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha Vencimiento Tecnicomecanica'),
        ),
    ]
