# Generated by Django 4.1.1 on 2022-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_activoequipooficina_fotoequipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activovehiculo',
            old_name='fotoEquipo',
            new_name='fotoVehiculo',
        ),
    ]
