# Generated by Django 4.1.1 on 2022-11-15 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_rename_fotoequipo_activovehiculo_fotovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoextintor',
            name='fechaProximaRecarga',
            field=models.DateField(default=datetime.date.today, help_text='DD/MM/AAAA', verbose_name='Fecha Proxima Recarga '),
        ),
    ]
