# Generated by Django 4.1.1 on 2022-11-15 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_activoextintor_fechaproximarecarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoextintor',
            name='fechaUltimaRecarga',
            field=models.DateField(default=datetime.date.today, help_text='DD/MM/AAAA', verbose_name='Fecha Ultima Recarga'),
        ),
        migrations.AlterField(
            model_name='activoextintor',
            name='fechaProximaRecarga',
            field=models.DateField(default=datetime.date.today, help_text='DD/MM/AAAA', verbose_name='Fecha Proxima Recarga'),
        ),
    ]
