# Generated by Django 4.1.1 on 2022-11-15 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_activoextintor_fechaultimarecarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activovehiculo',
            name='fechaProximoMantenimiento',
            field=models.DateField(default=datetime.date.today, help_text='DD/MM/AAAA', verbose_name='Fecha Proximo Mantenimiento'),
        ),
    ]
