# Generated by Django 4.1.1 on 2022-11-15 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_activovehiculo_fechaproximomantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoequipooficina',
            name='fechaProximaRevision',
            field=models.DateField(default=datetime.date.today, help_text='DD/MM/AAAA', verbose_name='Fecha Proxima Revisión'),
        ),
    ]
