# Generated by Django 4.1.1 on 2022-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_activoequipooficina_fechaproximarevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activoextintor',
            name='fotoExtintor',
            field=models.ImageField(blank=True, default='extintores/extintor_default.jpg', upload_to='extintores'),
        ),
    ]
