# Generated by Django 4.1.1 on 2022-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_alter_activoextintor_fotoextintor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activoextintor',
            name='fotoExtintor',
            field=models.ImageField(blank=True, default='extintores/extintores_default.jpg', upload_to='extintores'),
        ),
    ]
