# Generated by Django 4.1.1 on 2022-11-17 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_remove_activoequipooficina_fechaproximarevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoextintor',
            name='fechaUltimaRecarga',
            field=models.DateField(default=datetime.date.today, help_text='DD/MM/AAAA', verbose_name='Fecha Ultima Recarga'),
        ),
    ]
