# Generated by Django 4.1.1 on 2022-11-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_activoextintor_fechaultimarecarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activoequipooficina',
            name='memoriaEquipo',
            field=models.CharField(blank=True, default='No Aplica', max_length=20, verbose_name='Memoria del Equipo'),
        ),
        migrations.AlterField(
            model_name='activoequipooficina',
            name='ramEquipo',
            field=models.CharField(blank=True, default='No Aplica', max_length=20, verbose_name='Ram del Equipo'),
        ),
        migrations.AlterField(
            model_name='activoequipooficina',
            name='sistemaOperativo',
            field=models.CharField(blank=True, default='No Aplica', max_length=20, verbose_name='Sistema Operativo'),
        ),
    ]
