# Generated by Django 4.1.1 on 2022-11-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_alter_activoextintor_pesoextintor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activoequipooficina',
            name='componentesAdicionales',
            field=models.TextField(blank=True, max_length=200, verbose_name='Componentes del Equipo'),
        ),
    ]
