# Generated by Django 4.1.1 on 2022-11-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0021_activoequipooficina_fechaingresoequipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activovehiculo',
            name='serialVehiculo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial del Vehiculo'),
        ),
    ]
