# Generated by Django 4.1.1 on 2022-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0022_alter_activovehiculo_serialvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activoextintor',
            name='serialExtintor',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Extintor'),
        ),
    ]
